//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class access
    {
        public int ac_id { get; set; }
        public int v_id { get; set; }
        public int p_id { get; set; }
        public int u_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual policy policy { get; set; }
        public virtual user user { get; set; }
        public virtual version version { get; set; }
    }
}
