//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminSiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.accesses = new HashSet<access>();
            this.policies = new HashSet<policy>();
            this.versions = new HashSet<version>();
        }
    
        public int u_id { get; set; }
        public int role { get; set; }
    
        public virtual ICollection<access> accesses { get; set; }
        public virtual ICollection<policy> policies { get; set; }
        public virtual ICollection<version> versions { get; set; }
    }
}
